//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableispro2
    {
        public string Айди { get; set; }
        public string КодЗаказ { get; set; }
        public string Датасоздания { get; set; }
        public string Времязаказ { get; set; }
        public string АйдиКлиент { get; set; }
        public string Услуга { get; set; }
        public string Статус { get; set; }
        public string Датазакрытия { get; set; }
        public string Времяпроката { get; set; }
    }
}
